-- ===========================================================================
-- FarmMall — MySQL / MariaDB schema (baseline)
-- ===========================================================================
-- Import this file via cPanel phpMyAdmin to build the full database schema on a
-- FRESH database:
--   phpMyAdmin -> select your database -> Import -> choose this file -> Go
--
-- This is the FIRST migration. Add subsequent schema changes as new numbered
-- .sql files in this folder (e.g. 0002-add-something.sql) and import them in
-- order. See README.md.
--
-- Conventions baked into the app (Sequelize):
--   * UUID primary/foreign keys are CHAR(36); values are generated by the app,
--     so there is no DB-side default for `id`.
--   * JSON columns carry no DB default (the app supplies defaults).
--   * Most tables use snake_case columns; `media` and `media_associations` use
--     camelCase columns intentionally — keep them exactly as written.
-- Engine: InnoDB (required for foreign keys). Charset: utf8mb4.
-- ===========================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE `users` (
  `id` CHAR(36) NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `phone_number` VARCHAR(20) NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `county` VARCHAR(100) NOT NULL,
  `sub_county` VARCHAR(100) NOT NULL,
  `profile_picture_url` TEXT NULL,
  `location_lat` DECIMAL(10,8) NULL,
  `location_lng` DECIMAL(11,8) NULL,
  `subscription_type` ENUM('free','premium') NOT NULL DEFAULT 'free',
  `subscription_expires_at` DATETIME NULL,
  `email_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `phone_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `role` ENUM('user','admin') NOT NULL DEFAULT 'user',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_idx` (`email`),
  UNIQUE KEY `users_phone_number_idx` (`phone_number`),
  KEY `users_county_idx` (`county`),
  KEY `users_sub_county_idx` (`sub_county`),
  KEY `users_subscription_type_idx` (`subscription_type`),
  KEY `users_created_at_idx` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- crop_varieties
-- ---------------------------------------------------------------------------
CREATE TABLE `crop_varieties` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `crop_type` VARCHAR(50) NOT NULL,
  `maturity_period_days` INT NOT NULL,
  `seed_size_1_bags_per_acre` INT NOT NULL,
  `seed_size_2_bags_per_acre` INT NOT NULL,
  `seed_size_1_cost_per_acre` DECIMAL(10,2) NULL,
  `seed_size_2_cost_per_acre` DECIMAL(10,2) NULL,
  `fertilizer_cost_per_acre` DECIMAL(10,2) NULL,
  `herbicide_cost_per_acre` DECIMAL(10,2) NULL,
  `fungicide_cost_per_acre` DECIMAL(10,2) NULL,
  `insecticide_cost_per_acre` DECIMAL(10,2) NULL,
  `labor_cost_per_acre` DECIMAL(10,2) NULL,
  `land_preparation_cost_per_acre` DECIMAL(10,2) NULL,
  `miscellaneous_cost_per_acre` DECIMAL(10,2) NULL,
  `average_yield_per_acre` DECIMAL(10,2) NULL,
  `cost_data_updated_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `crop_varieties_name_idx` (`name`),
  KEY `crop_varieties_type_idx` (`crop_type`),
  KEY `crop_varieties_maturity_idx` (`maturity_period_days`),
  KEY `crop_varieties_fertilizer_cost_idx` (`fertilizer_cost_per_acre`),
  KEY `crop_varieties_labor_cost_idx` (`labor_cost_per_acre`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- farms
-- ---------------------------------------------------------------------------
CREATE TABLE `farms` (
  `id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `location` VARCHAR(255) NULL,
  `location_lat` DECIMAL(10,8) NULL,
  `location_lng` DECIMAL(11,8) NULL,
  `size_acres` DECIMAL(8,2) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `farms_owner_id_idx` (`owner_id`),
  KEY `farms_location_idx` (`location`),
  CONSTRAINT `fk_farms_owner_id` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- production_cycles
-- ---------------------------------------------------------------------------
CREATE TABLE `production_cycles` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `farm_id` CHAR(36) NOT NULL,
  `crop_variety_id` CHAR(36) NOT NULL,
  `land_size_acres` DECIMAL(8,2) NOT NULL,
  `farm_location` VARCHAR(255) NULL,
  `farm_location_lat` DECIMAL(10,8) NULL,
  `farm_location_lng` DECIMAL(11,8) NULL,
  `planting_date` DATE NULL,
  `estimated_harvest_date` DATE NULL,
  `actual_harvest_date` DATE NULL,
  `status` ENUM('planning','active','harvested','archived') NOT NULL DEFAULT 'planning',
  `total_cost` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `total_yield_kg` DECIMAL(10,2) NULL,
  `expected_yield` DECIMAL(10,2) NULL,
  `expected_price_per_kg` DECIMAL(10,2) NULL,
  `actual_yield` DECIMAL(10,2) NULL,
  `actual_price_per_kg` DECIMAL(10,2) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `production_cycles_user_id_idx` (`user_id`),
  KEY `production_cycles_farm_id_idx` (`farm_id`),
  KEY `production_cycles_crop_variety_id_idx` (`crop_variety_id`),
  KEY `production_cycles_status_idx` (`status`),
  KEY `production_cycles_planting_date_idx` (`planting_date`),
  KEY `production_cycles_harvest_date_idx` (`estimated_harvest_date`),
  KEY `production_cycles_location_idx` (`farm_location_lat`,`farm_location_lng`),
  CONSTRAINT `fk_production_cycles_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_production_cycles_farm_id` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_production_cycles_crop_variety_id` FOREIGN KEY (`crop_variety_id`) REFERENCES `crop_varieties` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- activities
-- ---------------------------------------------------------------------------
CREATE TABLE `activities` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NULL,
  `production_cycle_id` CHAR(36) NOT NULL,
  `type` ENUM('planting','fertilizing','fertilization','weeding','pest_control','disease_control','irrigation','harvesting','soil_preparation','other') NOT NULL,
  `description` TEXT NULL,
  `scheduled_date` DATETIME NOT NULL,
  `completed_date` DATETIME NULL,
  `cost` DECIMAL(10,2) NULL DEFAULT 0,
  `labor_hours` DECIMAL(4,1) NULL,
  `labor_type` ENUM('manual-family','manual-hired','mechanized') NULL,
  `inputs` JSON NULL,
  `notes` TEXT NULL,
  `weather` JSON NULL,
  `status` ENUM('planned','in_progress','completed','cancelled') NOT NULL DEFAULT 'planned',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `activities_user_id_idx` (`user_id`),
  KEY `activities_production_cycle_id_idx` (`production_cycle_id`),
  KEY `activities_scheduled_date_idx` (`scheduled_date`),
  KEY `activities_status_idx` (`status`),
  KEY `activities_type_idx` (`type`),
  CONSTRAINT `fk_activities_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_activities_production_cycle_id` FOREIGN KEY (`production_cycle_id`) REFERENCES `production_cycles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- farm_collaborators
-- ---------------------------------------------------------------------------
CREATE TABLE `farm_collaborators` (
  `id` CHAR(36) NOT NULL,
  `farm_id` CHAR(36) NOT NULL,
  `collaborator_id` CHAR(36) NULL,
  `invite_email` VARCHAR(255) NULL,
  `invite_phone` VARCHAR(255) NULL,
  `role` ENUM('viewer','manager','worker','family_member','admin') NOT NULL DEFAULT 'viewer',
  `permissions` JSON NOT NULL,
  `status` ENUM('pending','active','inactive') NOT NULL DEFAULT 'pending',
  `invite_token` CHAR(36) NULL,
  `invite_expires_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `farm_collaborators_invite_token_idx` (`invite_token`),
  KEY `farm_collaborators_farm_id_idx` (`farm_id`),
  KEY `farm_collaborators_collaborator_id_idx` (`collaborator_id`),
  KEY `farm_collaborators_invite_email_idx` (`invite_email`),
  KEY `farm_collaborators_invite_phone_idx` (`invite_phone`),
  KEY `farm_collaborators_status_idx` (`status`),
  CONSTRAINT `fk_farm_collaborators_farm_id` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_farm_collaborators_collaborator_id` FOREIGN KEY (`collaborator_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- pest_analyses
-- ---------------------------------------------------------------------------
CREATE TABLE `pest_analyses` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `production_cycle_id` CHAR(36) NULL,
  `image_url` TEXT NOT NULL,
  `crop_type` VARCHAR(100) NOT NULL,
  `location_lat` DECIMAL(10,8) NULL,
  `location_lng` DECIMAL(11,8) NULL,
  `analysis_result` JSON NOT NULL,
  `confidence_score` DECIMAL(5,4) NOT NULL,
  `status` ENUM('processing','completed','failed') NOT NULL DEFAULT 'processing',
  `ai_model_version` VARCHAR(50) NOT NULL,
  `processing_time_ms` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `pest_analyses_user_id_idx` (`user_id`),
  KEY `pest_analyses_production_cycle_id_idx` (`production_cycle_id`),
  KEY `pest_analyses_created_at_idx` (`created_at`),
  CONSTRAINT `fk_pest_analyses_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_pest_analyses_production_cycle_id` FOREIGN KEY (`production_cycle_id`) REFERENCES `production_cycles` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- weather_requests
-- ---------------------------------------------------------------------------
CREATE TABLE `weather_requests` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `location_lat` DECIMAL(10,8) NOT NULL,
  `location_lng` DECIMAL(11,8) NOT NULL,
  `request_type` ENUM('current','forecast','historical') NOT NULL,
  `response_data` JSON NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `weather_requests_user_id_idx` (`user_id`),
  KEY `weather_requests_created_at_idx` (`created_at`),
  CONSTRAINT `fk_weather_requests_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- plant_identifications
-- ---------------------------------------------------------------------------
CREATE TABLE `plant_identifications` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `image_url` TEXT NOT NULL,
  `thumbnail_url` TEXT NULL,
  `original_filename` TEXT NULL,
  `latitude` DECIMAL(10,8) NULL,
  `longitude` DECIMAL(11,8) NULL,
  `identification_result` JSON NOT NULL,
  `confidence_score` DECIMAL(5,4) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `plant_identifications_user_id_idx` (`user_id`),
  KEY `plant_identifications_created_at_idx` (`created_at`),
  KEY `plant_identifications_confidence_score_idx` (`confidence_score`),
  CONSTRAINT `fk_plant_identifications_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- plant_health_assessments
-- ---------------------------------------------------------------------------
CREATE TABLE `plant_health_assessments` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `image_url` TEXT NOT NULL,
  `thumbnail_url` TEXT NULL,
  `original_filename` TEXT NULL,
  `latitude` DECIMAL(10,8) NULL,
  `longitude` DECIMAL(11,8) NULL,
  `health_assessment_result` JSON NOT NULL,
  `is_healthy` TINYINT(1) NULL,
  `diseases` JSON NULL,
  `treatment_suggestions` JSON NULL,
  `notes` TEXT NULL,
  `provider_metadata` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `plant_health_assessments_user_id_idx` (`user_id`),
  KEY `plant_health_assessments_created_at_idx` (`created_at`),
  KEY `plant_health_assessments_is_healthy_idx` (`is_healthy`),
  CONSTRAINT `fk_plant_health_assessments_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- soil_tests
-- ---------------------------------------------------------------------------
CREATE TABLE `soil_tests` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `farm_id` CHAR(36) NULL,
  `document_url` TEXT NOT NULL,
  `thumbnail_url` TEXT NULL,
  `original_filename` VARCHAR(255) NOT NULL,
  `analysis_result` JSON NULL,
  `status` ENUM('pending','analyzed','failed') NOT NULL DEFAULT 'pending',
  `ai_model_version` VARCHAR(50) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `soil_tests_user_id_idx` (`user_id`),
  KEY `soil_tests_farm_id_idx` (`farm_id`),
  KEY `soil_tests_status_idx` (`status`),
  KEY `soil_tests_created_at_idx` (`created_at`),
  CONSTRAINT `fk_soil_tests_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_soil_tests_farm_id` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- media  (NOTE: camelCase columns — the model uses underscored: false)
-- ---------------------------------------------------------------------------
CREATE TABLE `media` (
  `id` CHAR(36) NOT NULL,
  `userId` CHAR(36) NOT NULL,
  `fileName` VARCHAR(255) NOT NULL,
  `originalName` VARCHAR(255) NOT NULL,
  `mimeType` VARCHAR(255) NOT NULL,
  `size` BIGINT NOT NULL,
  `hash` VARCHAR(64) NOT NULL,
  `status` ENUM('uploading','processing','ready','failed') NOT NULL DEFAULT 'uploading',
  `storageProvider` ENUM('supabase','local') NOT NULL DEFAULT 'supabase',
  `storagePath` VARCHAR(255) NOT NULL,
  `publicUrl` TEXT NULL,
  `variants` JSON NOT NULL,
  `metadata` JSON NOT NULL,
  `analytics` JSON NOT NULL,
  `isPublic` TINYINT(1) NOT NULL DEFAULT 0,
  `expiresAt` DATETIME NULL,
  `context` JSON NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `media_hash_unique_idx` (`hash`),
  KEY `media_user_id_idx` (`userId`),
  KEY `media_status_idx` (`status`),
  KEY `media_mime_type_idx` (`mimeType`),
  KEY `media_created_at_idx` (`createdAt`),
  CONSTRAINT `fk_media_user_id` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- media_associations  (camelCase columns; `order` is a reserved word)
-- ---------------------------------------------------------------------------
CREATE TABLE `media_associations` (
  `id` CHAR(36) NOT NULL,
  `mediaId` CHAR(36) NOT NULL,
  `associatableType` VARCHAR(255) NOT NULL,
  `associatableId` CHAR(36) NOT NULL,
  `role` VARCHAR(255) NOT NULL DEFAULT 'primary',
  `context` JSON NOT NULL,
  `order` INT NOT NULL DEFAULT 0,
  `metadata` JSON NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `media_associations_media_id_idx` (`mediaId`),
  KEY `media_associations_associatable_idx` (`associatableType`,`associatableId`),
  KEY `media_associations_type_id_role_idx` (`associatableType`,`associatableId`,`role`),
  -- Prefix lengths on the long VARCHAR columns keep the unique key under the
  -- InnoDB index key-length limit under utf8mb4.
  UNIQUE KEY `media_associations_unique_idx` (`mediaId`,`associatableType`(191),`associatableId`,`role`(191)),
  CONSTRAINT `fk_media_associations_media_id` FOREIGN KEY (`mediaId`) REFERENCES `media` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- preproduction_plans
-- ---------------------------------------------------------------------------
CREATE TABLE `preproduction_plans` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `planting_date` DATE NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `potato_variety` ENUM('Shangi','Sherekea','Unica','Markies') NOT NULL,
  `status` ENUM('not_started','in_progress','completed') NOT NULL DEFAULT 'not_started',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `preproduction_plans_user_id_idx` (`user_id`),
  KEY `preproduction_plans_status_idx` (`status`),
  CONSTRAINT `fk_preproduction_plans_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- preproduction_steps
-- ---------------------------------------------------------------------------
CREATE TABLE `preproduction_steps` (
  `id` CHAR(36) NOT NULL,
  `plan_id` CHAR(36) NOT NULL,
  `order` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `date_range_start` DATE NULL,
  `date_range_end` DATE NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `preproduction_steps_plan_id_idx` (`plan_id`),
  CONSTRAINT `fk_preproduction_steps_plan_id` FOREIGN KEY (`plan_id`) REFERENCES `preproduction_plans` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- preproduction_tasks
-- ---------------------------------------------------------------------------
CREATE TABLE `preproduction_tasks` (
  `id` CHAR(36) NOT NULL,
  `step_id` CHAR(36) NOT NULL,
  `order` INT NOT NULL DEFAULT 1,
  `title` VARCHAR(255) NOT NULL,
  `activity_type` ENUM('informational','task') NOT NULL DEFAULT 'task',
  `importance` TEXT NOT NULL,
  `recommendations` JSON NULL,
  `service_links` JSON NULL,
  `what_you_need` TEXT NULL,
  `what_you_need_link` TEXT NULL,
  `expert_tip` TEXT NULL,
  `completed` TINYINT(1) NOT NULL DEFAULT 0,
  `date_completed` DATE NULL,
  `cost` DECIMAL(12,2) NULL,
  `supplier` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `preproduction_tasks_step_id_idx` (`step_id`),
  CONSTRAINT `fk_preproduction_tasks_step_id` FOREIGN KEY (`step_id`) REFERENCES `preproduction_steps` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- events
-- ---------------------------------------------------------------------------
CREATE TABLE `events` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `date` DATETIME NOT NULL,
  `mode` ENUM('online','physical') NOT NULL,
  `location` TEXT NULL,
  `registration_link` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `created_by` CHAR(36) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `events_date_idx` (`date`),
  KEY `events_mode_idx` (`mode`),
  KEY `events_created_by_idx` (`created_by`),
  CONSTRAINT `fk_events_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
