const makeFile = (): Express.Multer.File => ({
  fieldname: 'image1',
  originalname: 'potato.jpg',
  encoding: '7bit',
  mimetype: 'image/jpeg',
  size: 12,
  buffer: Buffer.from('fake-image'),
  destination: '',
  filename: '',
  path: '',
  stream: null as any
});

export {};

const geminiResult = {
  healthStatus: {
    overall: 'diseased',
    isHealthy: false,
    healthScore: 52,
    confidence: 0.82,
    assessment: 'Gemini diagnosis',
    urgency: 'medium'
  },
  diseases: [
    {
      name: 'Gemini disease',
      commonNames: ['Gemini disease'],
      type: 'fungal',
      severity: 'moderate',
      confidence: 0.82,
      symptoms: ['Gemini symptom'],
      description: 'Generated disease description',
      causes: ['Gemini cause'],
      affectedParts: ['leaves'],
      stages: ['vegetative'],
      treatment: {
        immediate: ['Act now'],
        preventive: ['Prevent later'],
        prevention: ['Prevent later'],
        organic: ['Organic action'],
        chemical: ['Chemical action'],
        culturalPractices: ['Improve airflow']
      },
      prognosis: {
        treatability: 'moderate',
        timeline: '3 days',
        expectedOutcome: 'Improves with action'
      }
    }
  ],
  pests: [],
  nutritionalDeficiencies: [],
  environmentalStress: [],
  primaryConcerns: ['Gemini disease'],
  treatmentPriority: [],
  preventiveMeasures: ['Prevent later'],
  followUpRecommendations: ['Scout again'],
  analysisNotes: 'Generated by Gemini'
};

describe('PotatoDiseaseDetectionService', () => {
  const originalEnv = { ...process.env };
  let mockAssessPlantHealth: jest.Mock;

  const loadService = async () => {
    jest.resetModules();
    jest.doMock('../../../src/utils/logger', () => ({
      logError: jest.fn(),
      logInfo: jest.fn()
    }));
    mockAssessPlantHealth = jest.fn();
    jest.doMock('../../../src/services/gemini/plant-health.service', () => ({
      PlantHealthService: jest.fn().mockImplementation(() => ({
        assessPlantHealth: mockAssessPlantHealth
      }))
    }));
    return import('../../../src/services/potato-disease-detection.service');
  };

  beforeEach(() => {
    process.env = {
      ...originalEnv,
      HF_API_TOKEN: 'hf-token',
      HF_POTATO_MODEL_ID: 'test/potato-model',
      HF_POTATO_MIN_CONFIDENCE: '0.70',
      GEMINI_API_KEY: 'gemini-key'
    };
    global.fetch = jest.fn();
  });

  afterEach(() => {
    process.env = { ...originalEnv };
    jest.restoreAllMocks();
    jest.resetModules();
  });

  it('returns rule-set diagnosis for a known Hugging Face disease at 71% confidence without Gemini', async () => {
    (global.fetch as jest.Mock).mockResolvedValue({
      ok: true,
      json: async () => [{ label: 'Potato Early Blight', score: 0.71 }]
    });

    const { potatoDiseaseDetectionService } = await loadService();
    const result = await potatoDiseaseDetectionService.diagnose(makeFile());

    expect(result.success).toBe(true);
    expect(result.provider).toBe('huggingface');
    expect(result.confidence).toBe(0.71);
    expect(result.data?.diseases?.[0]?.name).toBe('Early blight');
    expect(mockAssessPlantHealth).not.toHaveBeenCalled();
  });

  it('falls back to Gemini for a known Hugging Face disease below 70% confidence', async () => {
    (global.fetch as jest.Mock).mockResolvedValue({
      ok: true,
      json: async () => [{ label: 'Potato Early Blight', score: 0.69 }]
    });
    const { potatoDiseaseDetectionService } = await loadService();
    mockAssessPlantHealth.mockResolvedValue({
      success: true,
      data: geminiResult,
      modelVersion: 'gemini-test',
      processingTime: 42
    });

    const result = await potatoDiseaseDetectionService.diagnose(makeFile());

    expect(result.success).toBe(true);
    expect(result.provider).toBe('gemini');
    expect(result.data?.diseases?.[0]?.name).toBe('Gemini disease');
    expect(mockAssessPlantHealth).toHaveBeenCalledTimes(1);
  });

  it('falls back to Gemini for an unsupported Hugging Face label even at high confidence', async () => {
    (global.fetch as jest.Mock).mockResolvedValue({
      ok: true,
      json: async () => [{ label: 'Potato Black Scurf', score: 0.95 }]
    });
    const { potatoDiseaseDetectionService } = await loadService();
    mockAssessPlantHealth.mockResolvedValue({
      success: true,
      data: geminiResult,
      modelVersion: 'gemini-test',
      processingTime: 39
    });

    const result = await potatoDiseaseDetectionService.diagnose(makeFile());

    expect(result.success).toBe(true);
    expect(result.provider).toBe('gemini');
    expect(result.providerMetadata.hfMetadata.normalized.key).toBe('unknown');
    expect(mockAssessPlantHealth).toHaveBeenCalledTimes(1);
  });

  it('falls back to Gemini when Hugging Face throws', async () => {
    (global.fetch as jest.Mock).mockRejectedValue(new Error('HF unavailable'));
    const { potatoDiseaseDetectionService } = await loadService();
    mockAssessPlantHealth.mockResolvedValue({
      success: true,
      data: geminiResult,
      modelVersion: 'gemini-test',
      processingTime: 55
    });

    const result = await potatoDiseaseDetectionService.diagnose(makeFile());

    expect(result.success).toBe(true);
    expect(result.provider).toBe('gemini');
    expect(result.providerMetadata.hfError.message).toBe('HF unavailable');
  });

  it('uses Gemini fallback by default when GEMINI_API_KEY exists and USE_GEMINI is unset', async () => {
    delete process.env.USE_GEMINI;
    (global.fetch as jest.Mock).mockRejectedValue(new Error('HF unavailable'));
    const { potatoDiseaseDetectionService } = await loadService();
    mockAssessPlantHealth.mockResolvedValue({
      success: true,
      data: geminiResult,
      modelVersion: 'gemini-test',
      processingTime: 61
    });

    const result = await potatoDiseaseDetectionService.diagnose(makeFile());

    expect(result.success).toBe(true);
    expect(result.provider).toBe('gemini');
    expect(result.providerMetadata.geminiEnabled).toBe(true);
    expect(mockAssessPlantHealth).toHaveBeenCalledTimes(1);
  });

  it('disables Gemini fallback only when USE_GEMINI=false', async () => {
    process.env.USE_GEMINI = 'false';
    (global.fetch as jest.Mock).mockRejectedValue(new Error('HF unavailable'));

    const { potatoDiseaseDetectionService } = await loadService();
    const result = await potatoDiseaseDetectionService.diagnose(makeFile());

    expect(result.success).toBe(false);
    expect(result.error).toContain('Hugging Face failed');
    expect(result.providerMetadata.hfError.message).toBe('HF unavailable');
    expect(result.providerMetadata.geminiEnabled).toBe(false);
    expect(result.providerMetadata.geminiDisabledReason).toBe('USE_GEMINI=false');
    expect(mockAssessPlantHealth).not.toHaveBeenCalled();
  });

  it('preserves the underlying Hugging Face fetch failure cause', async () => {
    process.env.USE_GEMINI = 'false';
    const fetchError: any = new Error('fetch failed');
    fetchError.cause = {
      message: 'getaddrinfo ENOTFOUND api-inference.huggingface.co',
      code: 'ENOTFOUND',
      errno: -3008,
      syscall: 'getaddrinfo',
      hostname: 'api-inference.huggingface.co'
    };
    (global.fetch as jest.Mock).mockRejectedValue(fetchError);

    const { potatoDiseaseDetectionService } = await loadService();
    const result = await potatoDiseaseDetectionService.diagnose(makeFile());

    expect(result.success).toBe(false);
    expect(result.providerMetadata.hfError.message).toBe('fetch failed');
    expect(result.providerMetadata.hfError.cause).toMatchObject({
      code: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'api-inference.huggingface.co'
    });
    expect(mockAssessPlantHealth).not.toHaveBeenCalled();
  });

  it('returns a clear failure when Hugging Face and Gemini are both unavailable', async () => {
    process.env.GEMINI_API_KEY = '';
    process.env.USE_GEMINI = 'false';
    (global.fetch as jest.Mock).mockRejectedValue(new Error('HF unavailable'));

    const { potatoDiseaseDetectionService } = await loadService();
    const result = await potatoDiseaseDetectionService.diagnose(makeFile());

    expect(result.success).toBe(false);
    expect(result.error).toContain('Hugging Face failed');
    expect(result.providerMetadata.hfError.message).toBe('HF unavailable');
    expect(result.providerMetadata.geminiDisabledReason).toBe('GEMINI_API_KEY not configured');
  });
});
